apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd/containers.pos
      format /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.*))? (?<log>.*)$/
      time_format %Y-%m-%dT%H:%M:%S.%L%z
      tag kube.*
      exclude_path /var/log/containers/fluent*
      # Uncomment the following line for debugging
      # read_from_head true
    </source>

    <match kube.**>
      @type elasticsearch
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME']}"
      logstash_format "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT']}"
      logstash_prefix "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX']}"
      ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY']}"
      # Uncomment the following line for debugging
      # buffer_chunk_limit 2M
      # buffer_queue_limit 8
    </match>
